### ISSUE TITLE
Synchronize version number to vert.x versions

### ISSUE THREAD

**Issue by gyszalai** [rhart/vertx-maven-plugin#16]
Vert.x changes at a very fast pace and many times I don't know which version of the maven plugin works with my vert.x version.

**Comment by rhart** [comment]
I know, I intend on improving this.  I will start to tag every time I update to the latest vertx version and make it clear what works with what

**Comment by rhart** [comment]
I have accepted your commits but the only problem I can see with syncing the versions is that there might need to be an extra number so I can release new versions of this plugin with fixes etc.  So for vertx 1.2.3 this plugin would be 1.2.3.0 and then 1.2.3.1, 1.2.3.2 etc.........thoughts?

Also, what is JURA releases?  I've never come across this before.

Thanks

**Comment by gyszalai** [comment]
The extra version number is a good idea. Yesterday I recreated version 1.2.3 three or four times in my fork just to stay in sync with vert.x. I used the maven-release-plugin so it was a pain...

The distributionManagement stuff with the jura repo in my pom refers to our own maven repo. Dont merge that. I decided to deploy my fork's builds here until the official version appears in maven central.

**Comment by rhart** [comment]
version updated to 1.2.3.1-SNAPSHOT

Next time I release (hopefully for a Maven Central release) I'll create a tag for 1.2.3.1-RELEASE and then increment to 1.2.3.2-SNAPSHOT

**Comment by rhart** [comment]
Hmmmm, I'm still undecided what to do here.  The problem arrises I think because the dependencies are not set to "provided" in the plugin.  Unless classes the plugin uses changes (which are only in the ......cli.. package) then the plugin should work with any version of vert.x.  I think since the very first release they have only changed once.

So, I'm thinking just to set them to provided in the plugin and then the project that uses the plugin can declare whatever version of vert.x they want.

Thoughts??

**Comment by gyszalai** [comment]
If the Vert.X platform for starting and/or deploying verticles and modules doesn't change, it could work.

**Comment by rhart** [comment]
I think I'm going to try that.  Otherwise I'll have to release new versions of the plugin even if nothing has changed.  That part of vert.x has only ever changed once and I imagine it's going to be a pretty stable part too.

If it doesnt work out then I'll go back to syncing the versions.

**Comment by rhart** [comment]
Actually I'm changing my mind again :)  I guess the purpose of the plugin is to provide a vert.x runtime and therefore it should have the dependencies.  Otherwise the verticle you are trying to build will have to include them and that doesnt seem right.
