### ISSUE TITLE
Modify maven groupId to org.vert-x to match the official vert.x goupId

### ISSUE THREAD

**Issue by gyszalai** [rhart/vertx-maven-plugin#17]
The Maven groupId has been changed from org.vertx to org.vert-x. If you agree, I'll do it and prepare the project to be deployed to Maven Central.

**Comment by rhart** [comment]
That would be great, I thought the same thing just havent had the time lately.

**Comment by gyszalai** [comment]
I started to work on preparing to deploy to Maven Central. These are the steps for doing it:
https://docs.sonatype.org/display/Repository/Sonatype+OSS+Maven+Repository+Usage+Guide
Please take a look at my prepare-maven-central branch.

Unfortunately there are steps that I cannot do, e.g. you have to generate a PGP keypair for signing 
artifacts, and registering your project on oss.sonytípe.org.

BTW, I'm not sure that org.vert-x can be used for groupId, because the Maven Central naming policy may prevent it.
It says you must be in full control of the domain that the groupId represents, i.e. you have to own the vert-x.org domain,
which you cannot, because it's owned by the vert.x project.

Please take a look at this (especially the **Policies for assigning groupIds to 3rd party artifacts** chapter):
https://docs.sonatype.org/display/Repository/Choosing+your+Coordinates

what do you think?

**Comment by rhart** [comment]
I'll go through the process and see how far I get.  Hudson/Jenkins plugins have the same problem but seem to get away with it.  I'll start tonight and keep the this issue updated with progress.

**Comment by rhart** [comment]
I've gone for org.vert-x.plugins after reading the guidelines.  Let's see what they say.....

**Comment by rhart** [comment]
I'm not allowed to use org.vert-x.plugins unless I get permission from the vert.x team.  Their suggestion is to potentially fork this plugin into the main vert.x code base.  I'm creating an issue to see if Tim agrees to this.  Failing that I will have to use my own group id

**Comment by rhart** [comment]
Using my own group Id while waiting on a decision whether this project will be accepted under the vertx main code base.

Group ID: org.anacoders.plugins
Artifact ID: vertx-maven-plugin
